var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "  x    xxxx                  xxxxx                xxx                         x ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x   x!!!!!!!!!!!!x ",
   "  xxxxxxxxxxxxxxxxxxxxxxvxxxxxxxxxxxxvxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxx ",
   "                      x   x        x   x                                        ",
   "                      x   x        x   x                                        ",
   "                      x!!!x        x!!!x                                        ",
   "                      x!!!x        x!!!x                                        ",
   "                      xxvxx        xxvxx                                        ",
   "                                                                                ",
   "                                                      y                         ",
   "                 o y o                     y        xxxxx                       ",
   "         *                                xxxxx                                  ",
   "         *  y    xxxxxxx                                                      x  ",
   "  x  @   *                       o                           o          o   o x  ",
   "  xxxxxxxxxxxxx           xxxxxxxxxxxx       xxxxxxxxx     xxx        xx  xxxx  ",
   "                                                              x!!!!!!x          ",
   "                                                               xxxxxx           ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!x                        xxxxxxx                                    x!x  ",
   "                                                                                                             x!x  ",
   "                                                                                                             x!x  ",
   "                                                                                                             x!x  ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  xxxxxxxxxx!!x                                                        x!x  ",
   "                                                xx!x                                                         x!x  ",
   "                                                 x!x                                            xxxxxxxxxxxxx!!x  ",
   "                                                 xvx               x   x                        !!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xx            v                        ",
   "                                                               xxxx!!!!!xxxx                                      ",
   "                                                                  xxxxxxx                                         ",
   "                                               xx                                                                 ",
   "                  o                            x                                                                  ",
   "              oxxxxxxxo       xxx   xxx        x                                             x                    ",
   "             oxx     xxo                       x           xxxxxx                            x                    ",
   "             xx       xx        x   x          x    xx                                       x                    ",
   "     @       x         x        x   x          x     x                     o         o       x                    ",
   "    xxx      x         x        x   x          x     x                   xxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx   xx         x     x               x           x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x    o    x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx xxxxx xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !                    xx!!!!!!xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx   o   xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  x                                                                                                        x  ",
   "  x                                 o                                                            x         x  ",
   "  x                                xxx                                   o                      xxx        x  ",
   "  x                           xxxxxxxxxxxxx  x    x    x    xxxxxx     xxxxx                     o         x  ",
   "  x      @       x  o x       x           x!!x o  x!!!!x o  x!!!!x    xx   xx                              x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x   xxxxxxxxx   xxxxxxxxx   xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=     =      =x   xxxxx                 xxx                                                          ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxx!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
